version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - messaging-network

  order-service:
    build:
      context: ./order-service
    depends_on:
      - rabbitmq
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - messaging-network

  payment-service:
    build:
      context: ./payment-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - messaging-network

networks:
  messaging-network:
    driver: bridge

